---
title: "3D Area Chart Demo"
---

This is a demo of a 3D area chart.

Highcharts Demos: [3D area chart](https://www.highcharts.com/demo/3d-area-multiple)

# Load packages

```{r}
#| label: load-packages
#| output: false

library(magrittr)
library(highcharter)
```

# Build data

```{r}
#| label: build-data

# Data for Tatra Mountains visible from Rusinowa polana
rusinowa_polana <- list(
  list("Murań", 1890),
  list("Nowy Wierch", 2009),
  list("Hawrań", 2152),
  list("Płaczliwa Skała", 2142),
  list("Szalony Wierch", 2061),
  list("Karczmarski Wierch", 1438),
  list("Jagnięcy Szczyt", 2230),
  list("Czerwona Turnia", 2284),
  list("Kołowy Szczyt", 2418),
  list("Czarny Szczyt", 2429),
  list("Baranie Rogi", 2526),
  list("Śnieżny Szczyt", 2465),
  list("Lodowy Szczyt", 2627),
  list("Lodowa Kopa", 2602),
  list("Szeroka Jaworzyńska", 2210),
  list("Horwacki Wierch", 1902),
  list("Spismichałowa Czuba", 2012),
  list("Zielona Czuba", 2130),
  list("Wielicki Szczyt", 2318),
  list("Gerlach", 2655),
  list("Batyżowiecki Szczyt", 2448),
  list("Kaczy Szczyt", 2395),
  list("Zmarzły Szczyt", 2390),
  list("Kończysta", 2538),
  list("Młynarz", 2170),
  list("Ganek", 2462),
  list("Wysoka", 2547),
  list("Ciężki Szczyt", 2520),
  list("Rysy", 2503),
  list("Żabi Mnich", 2146),
  list("Żabi Koń", 2291),
  list("Żabia Turnia Mięguszowiecka", 2335),
  list("Wołowa Turnia", 2373)
)

# Data for Dachstein panorama seen from Krippenstein
krippenstein <- list(
  list("Kufstein", 2049),
  list("Hohe Wildstelle", 2746),
  list("Kleiner Miesberg", 2173),
  list("Großer Miesberg", 2202),
  list("Hochstein", 2543),
  list("Lackner Miesberg", 2232),
  list("Wasenspitze", 2257),
  list("Sinabell", 2349),
  list("Feister Scharte", 2198),
  list("Eselstein", 2556),
  list("Landfriedstein", 2536),
  list("Scheichenspitz", 2667),
  list("Schmiedstock", 2634),
  list("Gamsfeldspitze", 2611),
  list("Edelgriess", 2305),
  list("Koppenkarstein", 2863),
  list("Niederer Gjaidstein", 2483),
  list("Hoher Gjaidstein", 2794),
  list("Hoher Dachstein", 2995),
  list("Niederer Dachstein", 2934),
  list("Hohes Kreuz", 2837),
  list("Hoher Ochsenkogel", 2513)
)

# Data for panorama from Col Des Mines
col_des_mines <- list(
  list("Combin de la Tsessette", 4141),
  list("Grand Combin de Grafeneire", 4314),
  list("Combin de Corbassière", 3716),
  list("Petit Combin", 3672),
  list("Pointe de Boveire", 3212),
  list("Grand Aget", 3133),
  list("Mont Rogneux", 3084),
  list("Dents du Grand Lé", 2884),
  list("Monts Telliers", 2951),
  list("Grand Golliat", 3238),
  list("Mont Grande Rochère", 3326),
  list("Mont de la Fouly", 2871),
  list("Tête de la Payanne", 2452),
  list("Pointe Allobrogia", 3172),
  list("Six Blanc", 2334),
  list("Mont Dolent", 3820),
  list("Aiguille de Triolet", 3870),
  list("Le Tour Noir", 3836),
  list("Aiguille de l\"A Neuve", 3753),
  list("Aiguille d\"Argentière", 3900),
  list("Aiguille du Chardonnet", 3824),
  list("Aiguille du Tour", 3540),
  list("Aiguille du Pissoir", 3440),
  list("Le Catogne", 2598),
  list("Pointe de Prosom", 2762),
  list("Pointe Ronde", 2700),
  list("Mont Buet", 3096),
  list("Le Cheval Blanc", 2831),
  list("Pointe de la Finive", 2838),
  list("Pic de Tenneverge", 2985),
  list("Pointe d\"Aboillon", 2819),
  list("Tour Sallière", 3220),
  list("Le Dôme", 3138),
  list("Haute Cime", 3257),
  list("Pierre Avoi", 2473),
  list("Cime de l\"Est", 3178)
)
```

# Set options

```{r}
#| label: set-options

options(
  highcharter.chart = list(
    accessibility = list(
      enabled = TRUE,
      linkedDescription = "The chart is showing the shapes of three mountain ranges as three area line series laid out in 3D behind each other.",
      keyboardNavigation = list(
        seriesNavigator = list(
          mode = "serialize"
        )
      )
    )
  ),
  highcharter.lang = list(
    accessibility = list(
      enabled = TRUE,
      axis = list(
        xAxisDescriptionPlural = "The chart has 3 unlabelled X axes, one for each series."
      )
    )
  )
)
```

# 3D area chart

```{r}
#| label: 3d-area

highchartzero() %>% 
  hc_add_dependency("highcharts-3d.js") %>% 
  hc_add_dependency("modules/exporting.js") %>% 
  hc_add_dependency("modules/export-data,js") %>% 
  hc_add_dependency("modules/accessibility.js") %>% 
  hc_chart(
    type = "area",
    options3d = list(
      enabled = TRUE,
      alpha = 15,
      beta = 30,
      depth = 200
    )
  ) %>% 
  hc_title(
    text = "Visual comparison of Mountains Panorama"
  ) %>% 
  hc_xAxis_multiples(
    list(
      visible = FALSE
    ),
    list(
      visible = FALSE
    ),
    list(
      visible = FALSE
    )
  ) %>%
  hc_yAxis(
    title = list(
      text = "Height Above Sea Level",
      x = -40
    ),
    labels = list(
      format = "{value:,.0f} MAMSL"
    ),
    gridLineDashStyle = "Dash"
  ) %>% 
  hc_plotOptions(
    area = list(
      depth = 100,
      marker = list(
        enabled = FALSE
      ),
      states = list(
        inactive = list(
          enabled = FALSE
        )
      )
    )
  ) %>% 
  hc_tooltip(
    valueSuffix = " MAMSL"
  ) %>% 
  hc_add_series(
    name = "Tatra Mountains visible from Rusinowa polana",
    lineColor = "rgb(180, 90, 50)",
    color = "rgb(200, 110, 50)",
    fillColor = "rgb(200, 110, 50)",
    data = rusinowa_polana
  ) %>% 
  hc_add_series(
    name = "Dachstein panorama seen from Krippenstein",
    xAxis = 1,
    lineColor = "rgb(120, 160, 160)",
    color = "rgb(140, 180, 200)",
    fillColor = "rgb(140, 180, 200)",
    data = krippenstein
  ) %>% 
  hc_add_series(
    name = "Panorama from Col Des Mines",
    xAxis = 2,
    lineColor = "rgb(200, 190, 140)",
    color = "rgb(200, 190, 140)",
    fillColor = "rgb(230, 220, 180)",
    data = col_des_mines
  )
```
