---
title: "3D Column Chart with null and 0 Values Demo"
---

This is a demo of a 3D column chart with null and 0 values.

Highcharts Demos: [3D column with null and 0 values](https://www.highcharts.com/demo/3d-column-null-values)

# Load packages

```{r}
#| label: load-packages
#| output: false

library(tibble)
library(highcharter)
```

# Build data

```{r}
#| label: build-data

df <- tibble(
  country = c(
    "Belgium", "China", "Denmark", "Fiji", "Germany", "Netherlands", "Russia", 
    "Sweden", "Turkey", "United States", "Unspecified", "Vietnam"
  ),
  total_imports = c(
    16076, 112688, 39452, 0, 94352, 30495, 21813, 
    95908, 11596, 53771, NA, 8270
  )
)
```

# Set options

```{r}
#| label: set-options

options(
  highcharter.chart = list(
    accessibility = list(
      enabled = TRUE,
      linkedDescription = "Chart designed to show the difference between 0 and null in a 3D column chart. A null point represents missing data, while 0 is a valid value."
    )
  )
)
```

# Highcharts Version 11 default color palette

```{r}
#| label: version-11-colors

colors_v11 <- c("#2caffe", "#544fc5", "#00e272", "#fe6a35", "#6b8abc", "#d568fb", "#2ee0ca", "#fa4b42", "#feb56a", "#91e8e1")
```

# 3D column chart with null and 0 values

```{r}
#| label: 3d-column-with-null-zero-values

highchartzero() %>% 
  hc_add_dependency("highcharts-3d.js") %>% 
  hc_add_dependency("modules/exporting.js") %>% 
  hc_add_dependency("modules/export-data,js") %>% 
  hc_add_dependency("modules/accessibility.js") %>% 
  hc_colors(colors = colors_v11) %>% 
  hc_chart(
    options3d = list(
      enabled = TRUE,
      alpha = 10,
      beta = 25,
      depth = 70
    )
  ) %>% 
  hc_title(
    text = "External trade in goods by country, Norway 2021",
    align = "left"
  ) %>% 
  hc_subtitle(
    text = "Source: <a href='https://www.ssb.no/en/statbank/table/08804'>SSB</a>",
    align = "left"
  ) %>% 
  hc_xAxis(
    title = list(
      text = NULL
    ),
    labels = list(
      skew3d = TRUE,
      style = list(
        fontSize = "16px"
      )
    )
  ) %>% 
  hc_yAxis(
    title = list(
      text = "NOK (million)",
      margin = 20
    )
  ) %>% 
  hc_plotOptions(
    column = list(
      depth = 25
    )
  ) %>% 
  hc_tooltip(
    valueSuffix = " MNOK"
  ) %>% 
  hc_add_series(
    data = df,
    type = "column",
    hcaes(x = country, y = total_imports),
    name = "Total imports",
    showInLegend = TRUE
  ) 
```
