---
title: "3D Column Chart Demo"
---

This is a demo of a 3D column chart.

Highcharts Demos: [3D column](https://www.highcharts.com/demo/3d-column-interactive)

# Load packages

```{r}
#| label: load-packages
#| output: false

library(tibble)
library(highcharter)
```

# Build data

```{r}
#| label: build-data

df <- tibble(
  brand = c(
    "Toyota", "BMW", "Volvo", "Audi", "Peugeot", "Mercedes-Benz", 
    "Volkswagen", "Polestar", "Kia", "Nissan"
  ),
  sold_passenger_cars = c(
    1318, 1073, 1060, 813, 775, 745, 
    537, 444, 416, 395
  )
)
```

# Set options

```{r}
#| label: set-options

options(
  highcharter.chart = list(
    accessibility = list(
      enabled = TRUE,
      linkedDescription = "Chart designed to highlight 3D column chart rendering options. Move the sliders below to change the basic 3D settings for the chart. 3D column charts are generally harder to read than 2D charts, but provide an interesting visual effect."
    )
  )
)
```

# Highcharts Version 11 default color palette

```{r}
#| label: version-11-colors

colors_v11 <- c("#2caffe", "#544fc5", "#00e272", "#fe6a35", "#6b8abc", "#d568fb", "#2ee0ca", "#fa4b42", "#feb56a", "#91e8e1")
```

# 3D column chart

```{r}
#| label: 3d-column

highchartzero() %>% 
  hc_add_dependency("highcharts-3d.js") %>% 
  hc_add_dependency("modules/exporting.js") %>% 
  hc_add_dependency("modules/export-data,js") %>% 
  hc_add_dependency("modules/accessibility.js") %>% 
  hc_colors(colors = colors_v11) %>% 
  hc_chart(
    options3d = list(
      enabled = TRUE,
      alpha = 15,
      beta = 15,
      depth = 50,
      viewDistance = 25
    )
  ) %>% 
  hc_title(
    text = "Sold passenger cars in Norway by brand, January 2021",
    align = "left"
  ) %>% 
  hc_subtitle(
    text = "Source: <a href='https://ofv.no/registreringsstatistikk'>OFV</a>",
    align = "left"
  ) %>% 
  hc_xAxis(
    title = list(
      text = NULL
    )
  ) %>% 
  hc_yAxis(
    title = list(
      text = FALSE
    )
  ) %>% 
  hc_legend(
    enabled = FALSE
  ) %>% 
  hc_plotOptions(
    column = list(
      depth = 25
    )
  ) %>% 
  hc_tooltip(
    headerFormat = "<b>{point.key}</b><br>",
    pointFormat = "Cars sold: {point.y}"
  ) %>% 
  hc_add_series(
    data = df,
    type = "column",
    hcaes(x = brand, y = sold_passenger_cars),
    colorByPoint = TRUE
  ) 
```
