---
title: "Column Range Chart Demo"
---

This is a demo of a column range chart.

Highcharts Demos: [Column range](https://www.highcharts.com/demo/columnrange)

# Load packages

```{r}
#| label: load-packages
#| output: false

library(tibble)
library(dplyr)
library(forcats)
library(highcharter)
```

# Build data

```{r}
#| label: build-data

df <- tibble(
  Jan = c(-13.9, 5.2),
  Feb = c(-16.7, 10.6),
  Mar = c(-4.7, 11.6),
  Apr = c(-4.4, 16.8),
  May = c(-2.1, 27.2),
  Jun = c(5.9, 29.4),
  Jul = c(6.5, 29.1),
  Aug = c(4.7, 25.4),
  Sep = c(4.3, 21.6),
  Oct = c(-3.5, 15.1),
  Nov = c(-9.8, 12.5),
  Dec = c(-11.5, 8.4)
) %>% 
  t() %>% 
  as_tibble(
    rownames = "month"
  ) %>% 
  rename(
    low = V1,
    high = V2
  ) %>% 
  mutate(
    month = as_factor(month)
  )

# Categories for x-axis
categories <- unique(df$month)
```

# Set options

```{r}
#| label: set-options

options(
  highcharter.chart = list(
    accessibility = list(
      enabled = TRUE,
      linkedDescription = "Image description: A column range chart compares the monthly temperature variations throughout 2017 in Vik I Sogn, Norway. The chart is interactive and displays the temperature range for each month when hovering over the data. The temperature is measured in degrees Celsius on the X-axis and the months are plotted on the Y-axis. The lowest temperature is recorded in March at minus 10.2 Celsius. The lowest range of temperatures is found in December ranging from a low of minus 9 to a high of 8.6 Celsius. The highest temperature is found in July at 26.2 Celsius. July also has the highest range of temperatures from 6 to 26.2 Celsius. The broadest range of temperatures is found in May ranging from a low of minus 0.6 to a high of 23.1 Celsius."
    )
  )
)
```

# Highcharts Version 11 default color palette

```{r}
#| label: version-11-colors

colors_v11 <- c("#2caffe", "#544fc5", "#00e272", "#fe6a35", "#6b8abc", "#d568fb", "#2ee0ca", "#fa4b42", "#feb56a", "#91e8e1")
```

# Column range chart

```{r}
#| label: column-range

highchartzero() %>% 
  hc_add_dependency("highcharts-more.js") %>% 
  hc_add_dependency("modules/exporting.js") %>% 
  hc_add_dependency("modules/export-data.js") %>% 
  hc_add_dependency("modules/accessibility.js") %>% 
  hc_colors(colors = colors_v11) %>% 
  hc_chart(
    inverted = TRUE
  ) %>% 
  hc_title(
    text = "Temperature variation by month"
  ) %>% 
  hc_subtitle(
    text = "Observed in  Vik i Sogn, Norway, 2021 | Source: <a href='https://www.vikjavev.no/ver/'>Vikjavev</a>"
  ) %>% 
  hc_caption(
    text = "Chart showing ranges using horizontal columns. Each range is represented with a low and high value, with a bar between them."
  ) %>% 
  hc_xAxis(
    title = list(
      text = NULL
    ),
    categories = categories
  ) %>% 
  hc_yAxis(
    title = list(
      text = "Temperature (°C)"
    )
  ) %>% 
  hc_tooltip(
    valueSuffix = "°C"
  ) %>% 
  hc_plotOptions(
    columnrange = list(
      borderRadius = 10,
      dataLabels = list(
        enabled = TRUE,
        format = "{y}°C"
      )
    )
  ) %>% 
  hc_legend(
    enabled = FALSE
  ) %>% 
  hc_add_series(
    data = df,
    type = "columnrange", 
    hcaes(x = month, low = low, high = high),
    name = "Temperatures"
  ) 
```
