---
title: "Stacked Percentage Column Chart Demo"
---

This is a demo of a stacked percentage column chart.

Highcharts Demos: [Stacked percentage column](https://www.highcharts.com/demo/column-stacked-percent)

# Load packages

```{r}
#| label: load-packages
#| output: false

library(tidyr)
library(dplyr)
library(forcats)
library(highcharter)
```

# Build data

```{r}
#| label: build-data

df <- tibble(
  season = c("2021/22", "2020/21", "2019/20", "2018/19", "2017/18"),
  `Kevin De Bruyne` = c(4, 4, 2, 4, 4),
  `Joshua Kimmich` = c(0, 4, 3, 2, 3),
  `Sadio Mané` = c(1, 2, 2, 1, 2)
) %>% 
  pivot_longer(
    cols = !season,
    names_to = "player",
    values_to = "assists"
  ) %>% 
  mutate(
    season = as_factor(season),
    player = as_factor(player),
    assists = as.integer(assists)
  )
```

# Set options

```{r}
#| label: set-options

options(
  highcharter.chart = list(
    accessibility = list(
      enabled = TRUE,
      linkedDescription = "Chart showing stacked percentage columns, where each column totals 100%, and each element value is visualized by giving it a size relative to the other elements."
    )
  )
)
```

# Highcharts Version 11 default color palette

```{r}
#| label: version-11-colors

colors_v11 <- c("#2caffe", "#544fc5", "#00e272", "#fe6a35", "#6b8abc", "#d568fb", "#2ee0ca", "#fa4b42", "#feb56a", "#91e8e1")
```

# Stacked percentage column chart

```{r}
#| label: stacked-percentage-column

highchartzero() %>% 
  hc_add_dependency("modules/exporting.js") %>% 
  hc_add_dependency("modules/export-data.js") %>% 
  hc_add_dependency("modules/accessibility.js") %>% 
  hc_colors(colors = colors_v11) %>% 
  hc_title(
    text = "UEFA CL most assists by season"
  ) %>% 
  hc_xAxis(
    title = list(
      text = NULL
      )
  ) %>% 
  hc_yAxis(
    title = list(
      text = "Assists"
    ),
    min = 0
  ) %>% 
  hc_tooltip(
    pointFormat = "<span style='color:{series.color}'>{series.name}</span>: <b>{point.y}</b> ({point.percentage:.0f}%)<br/>",
    shared = TRUE
  ) %>% 
  hc_plotOptions(
    column = list(
      stacking = "percent"
    )
  ) %>% 
  hc_add_series(
    data = df,
    type = "column",
    hcaes(x = season, y = assists, group = player)
  ) 
```
