---
title: "Bell Curve with Intervals Demo"
---

This is a demo of a chart showing a bell curve with intervals.

Highcharts Docs: [Setting the Bell Curve](https://www.highcharts.com/docs/chart-and-series-types/bell-curve-series#setting-the-bell-curve)

Highcharts Samples: [Bell Curve `intervals` and `pointsInInterval`](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/plotoptions/bellcurve-intervals-pointsininterval)

# Load packages

```{r}
#| label: load-packages
#| output: false

library(magrittr)
library(highcharter)
```

# Build data

```{r}
#| label: build-data

df <- c(
  3.5, 3, 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1, 3.7, 3.4, 3, 3, 4,
  4.4, 3.9, 3.5, 3.8, 3.8, 3.4, 3.7, 3.6, 3.3, 3.4, 3, 3.4, 3.5, 3.4, 3.2,
  3.1, 3.4, 4.1, 4.2, 3.1, 3.2, 3.5, 3.6, 3, 3.4, 3.5, 2.3, 3.2, 3.5, 3.8, 3,
  3.8, 3.2, 3.7, 3.3, 3.2, 3.2, 3.1, 2.3, 2.8, 2.8, 3.3, 2.4, 2.9, 2.7, 2, 3,
  2.2, 2.9, 2.9, 3.1, 3, 2.7, 2.2, 2.5, 3.2, 2.8, 2.5, 2.8, 2.9, 3, 2.8, 3,
  2.9, 2.6, 2.4, 2.4, 2.7, 2.7, 3, 3.4, 3.1, 2.3, 3, 2.5, 2.6, 3, 2.6, 2.3,
  2.7, 3, 2.9, 2.9, 2.5, 2.8, 3.3, 2.7, 3, 2.9, 3, 3, 2.5, 2.9, 2.5, 3.6,
  3.2, 2.7, 3, 2.5, 2.8, 3.2, 3, 3.8, 2.6, 2.2, 3.2, 2.8, 2.8, 2.7, 3.3, 3.2,
  2.8, 3, 2.8, 3, 2.8, 3.8, 2.8, 2.8, 2.6, 3, 3.4, 3.1, 3, 3.1, 3.1, 3.1, 2.7,
  3.2, 3.3, 3, 2.5, 3, 3.4, 3
)

# Set points in interval
pointsInInterval <- 5
```

# Set options

```{r}
#| label: set-options

options(
  highcharter.chart = list(
    accessibility = list(
      enabled = TRUE,
      linkedDescription = "Chart showing the use of a bell curve computed automatically from a dataset. The source dataset is visualized as a scatter plot. The demo visualizes four intervals for each side of the bell curve, and five points between each Nxσ."
    )
  )
)
```

# Highcharts Version 11 default color palette

```{r}
#| label: version-11-colors

colors_v11 <- c("#2caffe", "#544fc5", "#00e272", "#fe6a35", "#6b8abc", "#d568fb", "#2ee0ca", "#fa4b42", "#feb56a", "#91e8e1")
```

# Bell curve with `intervals` and `pointsInInterval`

```{r}
#| label: bell-curve-with-intervals

highchartzero() %>% 
  hc_add_dependency("modules/histogram-bellcurve.js") %>% 
  hc_add_dependency("modules/accessibility.js") %>% 
  hc_colors(colors = colors_v11) %>% 
  hc_chart(
    margin = c(50, 0, 50, 50),
    events = list(
      load = JS(
        "function () {
          Highcharts.each(this.series[0].data, function (point, i) {
            var labels = ['4σ', '3σ', '2σ', 'σ', 'μ', 'σ', '2σ', '3σ', '4σ'];
            if (i % pointInInterval === 0) {
              point.update({
                color: 'black',
                dataLabels: {
                  enabled : true,
                  format: labels[Math.floor(i / pointsInInterval)],
                  overflow: 'none',
                  crop: false,
                  y: -2,
                  style: {
                    fontSize: '13px'
                  }
                }
              })
            }
          })
        }"
      )
    )
  ) %>% 
  hc_title(
    text = NULL
  ) %>% 
  hc_legend(
    enabled = FALSE
  ) %>% 
  hc_xAxis_multiples(
    list(
      title = list(
        text = "Data"
      ),
      visible = FALSE
    ),
    list(
      title = list(
        text = "Bell curve"
      ),
      opposite = TRUE,
      visible = FALSE
    )
  ) %>% 
  hc_yAxis_multiples(
    list(
      title = list(
        text = "Data"
      ),
      visible = FALSE
    ),
    list(
      title = list(
        text = "Bell curve"
      ),
      opposite = TRUE,
      visible = FALSE
    )
  ) %>% 
  hc_add_series(
    name = "Bell curve", 
    type = "bellcurve",
    xAxis = 1,
    yAxis = 1,
    pointsInInterval = pointsInInterval,
    intervals = 4,
    baseSeries = 1,
    zIndex = -1,
    marker = list(
      enabled = TRUE
    )
  ) %>% 
  hc_add_series(
    name = "Data",
    type = "scatter",
    data = df,
    visible = FALSE,
    marker = list(
      radius = 1.5
    )
  )
```
