---
title: "Dependency Wheel Demo"
---

This is a demo of a chart showing a dependency wheel.

Highcharts Demos: [Dependency wheel](https://www.highcharts.com/demo/dependency-wheel)

# Load packages

```{r}
#| label: load-packages
#| output: false

library(tibble)
library(dplyr)
library(forcats)
library(highcharter)
```

# Build data

```{r}
#| label: build-data

df <- tibble(
  c("Brazil", "Portugal", 5),
  c("Brazil", "France", 1),
  c("Brazil", "Spain", 1),
  c("Brazil", "England", 1),
  c("Canada", "Portugal", 1),
  c("Canada", "France", 5),
  c("Canada", "England", 1),
  c("Mexico", "Portugal", 1),
  c("Mexico", "France", 1),
  c("Mexico", "Spain", 5),
  c("Mexico", "England", 1),
  c("USA", "Portugal", 1),
  c("USA", "France", 1),
  c("USA", "Spain", 1),
  c("USA", "England", 5),
  c("Portugal", "Angola", 2),
  c("Portugal", "Senegal", 1),
  c("Portugal", "Morocco", 1),
  c("Portugal", "South Africa", 3),
  c("France", "Angola", 1),
  c("France", "Senegal", 3),
  c("France", "Mali", 3),
  c("France", "Morocco", 3),
  c("France", "South Africa", 1),
  c("Spain", "Senegal", 1),
  c("Spain", "Morocco", 3),
  c("Spain", "South Africa", 1),
  c("England", "Angola", 1),
  c("England", "Senegal", 1),
  c("England", "Morocco", 2),
  c("England", "South Africa", 7),
  c("South Africa", "China", 5),
  c("South Africa", "India", 1),
  c("South Africa", "Japan", 3),
  c("Angola", "China", 5),
  c("Angola", "India", 1),
  c("Angola", "Japan", 3),
  c("Senegal", "China", 5),
  c("Senegal", "India", 1),
  c("Senegal", "Japan", 3),
  c("Mali", "China", 5),
  c("Mali", "India", 1),
  c("Mali", "Japan", 3),
  c("Morocco", "China", 5),
  c("Morocco", "India", 1),
  c("Morocco", "Japan", 3),
  c("Japan", "Brazil", 1)
) %>% 
  t() %>% 
  as_tibble() %>% 
  rename(
    from = V1, 
    to = V2, 
    weight = V3
  ) %>% 
  mutate(
    from = as_factor(from),
    to = as_factor(to),
    weight = as.integer(weight)
  )
```

# Set options

```{r}
#| label: set-options

options(
  highcharter.chart = list(
    accessibility = list(
      enabled = TRUE,
      linkedDescription = "Chart showing a dependency wheel, where each point consists of multiple weighted links to other points. This chart type is often used to visualize data flow, and can be a striking way to illustrate relationships in data.",
      point = list(
        valueDescriptionFormat = "{index}. From {point.from} to {point.to}: {point.weight}."
      )
    )
  )
)
```

# Highcharts Version 11 default color palette

```{r}
#| label: version-11-colors

colors_v11 <- c("#2caffe", "#544fc5", "#00e272", "#fe6a35", "#6b8abc", "#d568fb", "#2ee0ca", "#fa4b42", "#feb56a", "#91e8e1")
```

# Dependency wheel

```{r}
#| label: dependency-wheel

highchartzero() %>% 
  hc_add_dependency("modules/sankey.js") %>% 
  hc_add_dependency("modules/dependency-wheel.js") %>% 
  hc_add_dependency("modules/exporting.js") %>% 
  hc_add_dependency("modules/export-data.js") %>% 
  hc_add_dependency("modules/accessibility.js") %>% 
  hc_colors(colors = colors_v11) %>% 
  hc_title(
    text = "Highcharter Dependency Wheel"
  ) %>% 
  hc_add_series(
    data = df,
    type = "dependencywheel",
    hcaes(from = from, to = to, weight = weight),
    name = "Dependency wheel series",
    dataLabels = list(
      color = "#333",
      style = list(
        textOutline = "none"
      ),
      textPath = list(
        enabled = TRUE
      ),
      distance = 15
    ),
    size = "95%"
  )
```
