---
title: "Histogram Demo"
---

This is a demo of a histogram.

Highcharts Demos: [Histogram](https://www.highcharts.com/demo/histogram)

# Load packages

```{r}
#| label: load-packages
#| output: false

library(magrittr)
library(highcharter)
```

# Build data

```{r}
#| label: build-data

df <- c(
  3.5, 3, 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1, 3.7, 3.4, 3, 3,
  4, 4.4, 3.9, 3.5, 3.8, 3.8, 3.4, 3.7, 3.6, 3.3, 3.4, 3, 3.4, 3.5, 3.4,
  3.2, 3.1, 3.4, 4.1, 4.2, 3.1, 3.2, 3.5, 3.6, 3, 3.4, 3.5, 2.3, 3.2, 3.5,
  3.8, 3, 3.8, 3.2, 3.7, 3.3, 3.2, 3.2, 3.1, 2.3, 2.8, 2.8, 3.3, 2.4, 2.9,
  2.7, 2, 3, 2.2, 2.9, 2.9, 3.1, 3, 2.7, 2.2, 2.5, 3.2, 2.8, 2.5, 2.8, 2.9,
  3, 2.8, 3, 2.9, 2.6, 2.4, 2.4, 2.7, 2.7, 3, 3.4, 3.1, 2.3, 3, 2.5, 2.6,
  3, 2.6, 2.3, 2.7, 3, 2.9, 2.9, 2.5, 2.8, 3.3, 2.7, 3, 2.9, 3, 3, 2.5, 2.9,
  2.5, 3.6, 3.2, 2.7, 3, 2.5, 2.8, 3.2, 3, 3.8, 2.6, 2.2, 3.2, 2.8, 2.8, 2.7,
  3.3, 3.2, 2.8, 3, 2.8, 3, 2.8, 3.8, 2.8, 2.8, 2.6, 3, 3.4, 3.1, 3, 3.1,
  3.1, 3.1, 2.7, 3.2, 3.3, 3, 2.5, 3, 3.4, 3
)
```

# Set options

```{r}
#| label: set-options

options(
  highcharter.chart = list(
    accessibility = list(
      enabled = TRUE,
      linkedDescription = "Chart showing how Highcharts can automatically compute a histogram from source data. In this chart, the source data is also displayed as a scatter plot."
    )
  )
)
```

# Highcharts Version 11 default color palette

```{r}
#| label: version-11-colors

colors_v11 <- c("#2caffe", "#544fc5", "#00e272", "#fe6a35", "#6b8abc", "#d568fb", "#2ee0ca", "#fa4b42", "#feb56a", "#91e8e1")
```

# Histogram

```{r}
#| label: histogram

highchartzero() %>% 
  hc_add_dependency("modules/histogram-bellcurve.js") %>% 
  hc_add_dependency("modules/exporting.js") %>% 
  hc_add_dependency("modules/accessibility.js") %>% 
  hc_colors(colors = colors_v11) %>% 
  hc_title(
    text = "Highcharter Histogram"
  ) %>% 
  hc_xAxis_multiples(
    list(
      title = list(
        text = "Data"
      ),
      alignTicks = FALSE
    ),
    list(
      title = list(
        text = "Histogram"
      ),
      alignTicks = FALSE,
      opposite = TRUE
    )
  ) %>% 
  hc_yAxis_multiples(
    list(
      title = list(
        text = "Data"
      )
    ),
    list(
      title = list(
        text = "Histogram"
      ),
      opposite = TRUE
    )
  ) %>% 
  hc_plotOptions(
    histogram = list(
      accessibility = list(
        point = list(
          valueDescriptionFormat = "{index}. {point.x:.3f} to {point.x2:.3f}, {point.y}."
        )
      )
    )
  ) %>% 
  hc_add_series(
    name = "Histogram",
    type = "histogram",
    xAxis = 1,
    yAxis = 1,
    baseSeries = "s1",
    zIndex = -1
  ) %>% 
  hc_add_series(
    name = "Data",
    type = "scatter",
    data = df,
    id = "s1",
    marker = list(
      radius = 1.5
    )
  )
```
