---
title: "Radial Bar Chart with Stacked Inverted Bars Demo"
---

This is a demo of a radial bar chart with stacked and inverted polar bars.

Highcharts Docs: [Examples of use](https://www.highcharts.com/docs/chart-and-series-types/radial-bar-chart#examples-of-use)

Highcharts Samples: [Stacked inverted polar bars](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/series-polar/column-inverted-stacking)

# Load packages

```{r}
#| label: load-packages
#| output: false

library(magrittr)
library(highcharter)
```

# Set options

```{r}
#| label: set-options

options(
  highcharter.chart = list(
    accessibility = list(
      enabled = TRUE,
      linkedDescription = "A radial bar chart with stacked and inverted polar bars."
    )
  )
)
```

# Highcharts Version 11 default color palette

```{r}
#| label: version-11-colors

colors_v11 <- c("#2caffe", "#544fc5", "#00e272", "#fe6a35", "#6b8abc", "#d568fb", "#2ee0ca", "#fa4b42", "#feb56a", "#91e8e1")
```

# Radial bar chart with stacked and inverted polar bars

```{r}
#| label: radial-bar-stacked-inverted

highchartzero() %>% 
  hc_add_dependency("highcharts-more.js") %>%
  hc_add_dependency("modules/accessibility.js") %>% 
  hc_colors(colors = colors_v11) %>% 
  hc_chart(
    type = "column",
    inverted = TRUE,
    polar = TRUE,
    marginTop = 25
  ) %>% 
  hc_title(
    text = "Stacked inverted polar bars"
  ) %>% 
  hc_xAxis(
    tickInterval = 1,
    labels = list(
      y = 15
    )
  ) %>% 
  hc_yAxis(
    min = 0,
    max = 45
  ) %>% 
  hc_plotOptions(
    column = list(
      stacking = "normal",
      borderWidth = 0,
      pointPadding = 0,
      groupPadding = 0.15,
      pointPlacement = "between",
      dataLabels = list(
        enabled = TRUE,
        allowOverlap = TRUE,
        textPath = list(
          enabled = TRUE,
          attributes = list(
            textAnchor = "start",
            startOffset = 5,
            dy = 11.5
          )
        )
      )
    )
  ) %>% 
  hc_add_series(
    data = c(7, 6, 9, 14, 18, 21, 25, 26, 23, 18)
  ) %>% 
  hc_add_series(
    data = c(3, 4, 5, 8, 11, 15, 17, 16, 14, 10)
  )
```
