---
title: "Word Cloud Demo"
---

This is a demo of a word cloud.

Highcharts Demos: [Word cloud](https://www.highcharts.com/demo/wordcloud)

# Load packages

```{r}
#| label: load-packages
#| output: false

library(dplyr)
library(stringr)
library(purrr)
library(rvest)
library(tidytext)
library(highcharter)
```

# Scrape data

```{r}
#| label: scrape-data

df <- read_html("https://jkunst.com/highcharter/") %>% 
  html_nodes("p") %>% 
  html_text() %>% 
  map(str_to_lower) %>% 
  str_split("\\s+") %>% 
  unlist() %>% 
  tibble() %>% 
  setNames("word") %>% 
  count(word, sort = TRUE) %>% 
  anti_join(stop_words, by = "word") %>% 
  filter(!word == "") %>% 
  head(10)
```

# Set options

```{r}
#| label: set-options

options(
  highcharter.chart = list(
    accessibility = list(
      enabled = TRUE,
      linkedDescription = "Word clouds are used to visualize how often each word in a text occurs. This example uses the text scraped from the home page of the highcharter library website. Words that appear often will appear larger."
    )
  )
)
```

# Highcharts Version 11 default color palette

```{r}
#| label: version-11-colors

colors_v11 <- c("#2caffe", "#544fc5", "#00e272", "#fe6a35", "#6b8abc", "#d568fb", "#2ee0ca", "#fa4b42", "#feb56a", "#91e8e1")
```

# Word cloud

```{r}
#| label: word-cloud

highchartzero() %>% 
  hc_add_dependency("modules/wordcloud.js") %>% 
  hc_add_dependency("modules/exporting.js") %>% 
  hc_add_dependency("modules/export-data.js") %>% 
  hc_add_dependency("modules/accessibility.js") %>% 
  hc_colors(colors = colors_v11) %>% 
  hc_title(
    text = "Wordcloud of highcharter home page",
    align = "left"
  ) %>% 
  hc_tooltip(
    headerFormat = "<span style='font-size: 16px'><b>{point.key}</b></span><br>"
  ) %>% 
  hc_add_series(
    data = df,
    type = "wordcloud",
    hcaes(name = word, weight = n),
    name = "Occurrences"
  ) 
```
