---
title: "Spider Map Demo"
---

This is a demo of a spider map.

Highcharts Maps Demos: [Spider map](https://www.highcharts.com/demo/maps/spider-map)

# Load packages

```{r}
#| label: load-packages
#| output: false

library(magrittr)
library(highcharter)
```

# Build data

```{r}
#| label: build-data

df <- list(
  list("Atlanta", "USA", "1996", 33.75, -84.38, 7, 2, 2, 3),
  list("Sydney", "Australia", "2020", -33.87, 151.20, 10, 4, 3, 3),
  list("Athens", "Greece", "2004", 38, 23.72, 6, 5, 0, 1),
  list("Beijing", "China", "2008", 39.92, 116.38, 9, 3, 5, 1),
  list("London", "Great Britain", "2012", 51.5, -0.12, 4, 2, 1, 1),
  list("Rio de Janeiro", "Brazil", "2016", -22.91, -43.20, 4, 0, 0, 4),
  list("Tokyo", "Japan", "2020", 35.69, 139.69, 8, 4, 2, 2)
)
```

# Set options

```{r}
#| label: set-options

options(
  highcharter.chart = list(
    accessibility = list(
      enabled = TRUE,
      linkedDescription = "A spider map showing Norwegian medals in the Summer Olympics, 1996 to 2020."
    )
  )
)
```

# Highcharts Version 11 default color palette

```{r}
#| label: version-11-colors

colors_v11 <- c("#2caffe", "#544fc5", "#00e272", "#fe6a35", "#6b8abc", "#d568fb", "#2ee0ca", "#fa4b42", "#feb56a", "#91e8e1")
```

# Spider map

Issues:

-   Fix bullet (medal) color in tooltip

```{r}
#| label: spider-map

hcmap(
  map = "custom/world",
  download_map_data = getOption("highcharter.download_map_data"),
  nullColor = "#fad3cf"
) %>% 
  hc_legend(
    enabled = FALSE
  ) %>% 
  hc_mapNavigation(
    enabled = TRUE,
    buttonOptions = list(
      verticalAlign = "bottom"
    )
  ) %>% 
  hc_mapView(
    fitToGeometry = list(
      type = "MultiPoint",
      coordinates = list(
        list(-164, 54), # Alaska west
        list(-35, 84), # Greenland north
        list(179, -38), # New Zealand east
        list(-68, -55) # Chile south
      )
    )
  ) %>% 
  hc_title(
    text = "Norwegian medals in the Summer Olympics (1996 - 2020)",
    align = "left"
  ) %>% 
  hc_subtitle(
    text = "Source: <a href='https://en.wikipedia.org/wiki/Norway_at_the_Olympics'>Wikipedia</a>",
    align = "left"
  ) %>% 
  hc_tooltip(
    headerFormat = NULL,
    pointFormat = "{point.city} ({point.country}, {point.year})<br>Total medals: {point.z}<br><span style='color: #ffd700;'>\u25CF</span> {point.gold}<br><span style='color: #c0c0c0;'>\u25CF</span> {point.silver}<br><span style='color: #cd7f32;'>\u25CF</span> {point.bronze}<br>"
  ) %>% 
  hc_add_series(
    name = "Olympic games",
    type = "mapbubble",
    color = "#fe5f55",
    lineWidth = 1,
    keys = list(
      "city", "country", "year", "lat", "lon", "z", "gold", "silver", "bronze"
    ),
    data = df,
    minSize = "5%",
    maxSize = "12.5%",
    accessibility = list(
      point = list(
        valueDescriptionFormat = "{point.city}, {point.country}, {point.year}. Total medals: {point.z}. Gold: {point.gold}, silver: {point.silver}, bronze: {point.bronze}."
      )
    )
  )
```
