---
title: "Tile Map with Diamonds Demo"
---
This is a demo of a tile map with diamonds.

Highcharts Maps Demos: [Tile map, diamonds](https://www.highcharts.com/demo/maps/diamondmap)

# Load packages

```{r}
#| label: load-packages
#| output: false

library(magrittr)
library(jsonlite)
library(highcharter)
```

# Build data

```{r}
#| label: build-data

main_idea <- list(
  list(
    5, 3, "Main idea",
    "The main idea tile outlines the overall theme of the idea map."
  )
)

steps <- list(
  list(
    3, 3, "Step 1",
    "First step towards the main idea. Describe the starting point of the situation."
  ),
  list(
    4, 3, "Step 2",
    "Describe where to move next in a short term time perspective."
  ),
  list(
    5, 4, "Step 3",
    "This can be a larger milestone, after the initial steps have been taken."
  ),
  list(
    6, 3, "Step 4",
    "Evaluate progress and readjust the course of the project."
  ),
  list(
    7, 3, "Step 5",
    "At this point, major progress should have been made, and we should be well on our way to implementing the main idea."
  ),
  list(
    6, 2, "Step 6",
    "Second evaluation and readjustment step. Implement final changes."
  ),
  list(
    5, 2, "Step 7",
    "Testing and final verification step."
  ),
  list(
    4, 2, "Step 8",
    "Iterate after final testing and finalize implementation of the idea."
  )
)
```

# Set options

```{r}
#| label: set-options

options(
  highcharter.chart = list(
    accessibility = list(
      enabled = TRUE,
      linkedDescription = "Idea map, laid out as tiles with the main idea in the centre. Steps related to the main idea are shown as additional tiles circling the centre tile.",
      point = list(
        valueDescriptionFormat = "{point.name}. {point.desc}"
      )
    )
  )
)
```

# Tile map diamonds

```{r}
#| label: tile-map-diamonds

highchart() %>% 
  hc_chart(
    type = "tilemap",
    marginTop = 15,
    height = "65%"
  ) %>% 
  hc_title(
    text = "Idea map"
  ) %>% 
  hc_subtitle(
    text = "Hover over tiles for details"
  ) %>% 
  hc_colors(
    colors = c(
      "#fed",
      "#ffddc0",
      "#ecb",
      "#dba",
      "#c99",
      "#b88",
      "#aa7577",
      "#9f6a66"
    )
  ) %>% 
  hc_xAxis(
    visible = FALSE
  ) %>% 
  hc_yAxis(
    visible = FALSE
  ) %>% 
  hc_legend(
    enabled = FALSE
  ) %>% 
  hc_tooltip(
    headerFormat = "",
    backgroundColor = "rgba(247,247,247,0.95)",
    pointFormat = "<span style='color: {point.color}'>●</span> <span style='font-size: 13px; font-weight: bold'> {point.name} </span><br>{point.desc}",
    style = list(
      width = 170
    ),
    padding = 10,
    hideDelay = 1000000
  ) %>% 
  hc_plotOptions(
    tilemap = list(
      keys = list("x", "y", "name", "desc"),
      tileShape = "diamond",
      dataLabels = list(
        enabled = TRUE,
        format = "{point.name}",
        color = "#000000",
        style = list(
          textOutline = FALSE
        )
      )
    )
  ) %>% 
  hc_add_series(
    name = "Main idea",
    pointPadding = 10,
    data = main_idea,
    color = "#7eb"
  ) %>% 
  hc_add_series(
    name = "Steps",
    colorByPoint = TRUE,
    data = steps
  )
```
