---
title: "Stock Chart with Reversed Y-Axis Demo"
---

This is a demo of an area stock chart with reversed y-axis.

Highcharts Stock Demos: [Reversed Y axis](https://www.highcharts.com/demo/stock/yaxis-reversed)

# Load packages

```{r}
#| label: load-packages
#| output: false

library(magrittr)
library(quantmod)
library(highcharter)
```

# Import data

```{r}
#| label: import-data

aapl <- getSymbols("AAPL", auto.assign = FALSE)
```

# Set options

```{r}
#| label: set-options

options(
  highcharter.chart = list(
    accessibility = list(
      enabled = TRUE,
      linkedDescription = "An area stock chart showing Apple stock price. The chart has a reversed y-axis."
    )
  )
)
```

# Highcharts Version 11 default color palette

```{r}
#| label: version-11-colors

colors_v11 <- c("#2caffe", "#544fc5", "#00e272", "#fe6a35", "#6b8abc", "#d568fb", "#2ee0ca", "#fa4b42", "#feb56a", "#91e8e1")
```

# Reversed Y axis

```{r}
#| label: reversed-y-axis

highchart(type = "stock") %>% 
  hc_colors(colors = colors_v11) %>% 
  hc_rangeSelector(
    selected = 1
  ) %>% 
  hc_title(
    text = "AAPL Stock Price"
  ) %>% 
  hc_yAxis(
    reversed = TRUE,
    showFirstLabel = FALSE,
    showLastLabel = TRUE
  ) %>% 
  hc_add_series(
    type = "area",
    name = "AAPL Stock Price",
    data = aapl,
    threshold = NULL,
    tooltip = list(
      valueDecimals = 2
    ),
    fillColor = list(
      linearGradient = list(
        x1 = 0,
        y1 = 1,
        x2 = 0,
        y2 = 0
      ),
      stops = list(
        list(0, colors_v11[1]),
        list(1, adjustcolor(colors_v11[1], alpha.f = 0))
      )
    )
  )
```
