---
title: "Candlestick Stock Chart Demo"
---

This is a demo of a candlestick stock chart.

Highcharts Stock Demos: [Candlestick](https://www.highcharts.com/demo/stock/candlestick)

# Load packages

```{r}
#| label: load-packages
#| output: false

library(magrittr)
library(quantmod)
library(highcharter)
```

# Import data

```{r}
#| label: import-data

aapl <- getSymbols("AAPL", auto.assign = FALSE)
aapl <- adjustOHLC(aapl)
```

# Set options

```{r}
#| label: set-options

options(
  highcharter.chart = list(
    accessibility = list(
      enabled = TRUE,
      linkedDescription = "A candlestick stock chart showing Apple stock price."
    )
  )
)
```

# Highcharts Version 11 default color palette

```{r}
#| label: version-11-colors

colors_v11 <- c("#2caffe", "#544fc5", "#00e272", "#fe6a35", "#6b8abc", "#d568fb", "#2ee0ca", "#fa4b42", "#feb56a", "#91e8e1")
```

# Candlestick

```{r}
#| label: candlestick

highchart(type = "stock") %>% 
  hc_colors(colors = colors_v11) %>% 
  hc_rangeSelector(
    selected = 1
  ) %>% 
  hc_title(
    text = "AAPL Stock Price"
  ) %>% 
  hc_add_series(
    type = "candlestick",
    name = "AAPL Stock Price",
    data = aapl,
    dataGrouping = list(
      units = list(
        list(
          "week", # unit name
          list(1) # allowed multiples
        ),
        list(
          "month",
          list(1, 2, 3, 4, 6)
        )
      )
    )
  ) %>% 
  hc_tooltip(
    valueDecimals = 2
  )
```
