---
title: "Depth Stock Chart Demo"
---

This is a demo of a depth stock chart.

Highcharts Stock Demos: [Depth chart](https://www.highcharts.com/demo/stock/depth-chart)

# Load packages

```{r}
#| label: load-packages
#| output: false

library(magrittr)
library(highcharter)
```

# Build data

```{r}
#| label: build-data

bids <- list(
  c(0.1524, 0.948665),
  c(0.1539, 35.510715),
  c(0.154, 39.883437),
  c(0.1541, 40.499661),
  c(0.1545, 43.262994000000006),
  c(0.1547, 60.14799400000001),
  c(0.1553, 60.30799400000001),
  c(0.1558, 60.55018100000001),
  c(0.1564, 68.381696),
  c(0.1567, 69.46518400000001),
  c(0.1569, 69.621464),
  c(0.157, 70.398015),
  c(0.1574, 70.400197),
  c(0.1575, 73.199217),
  c(0.158, 77.700017),
  c(0.1583, 79.449017),
  c(0.1588, 79.584064),
  c(0.159, 80.584064),
  c(0.16, 81.58156),
  c(0.1608, 83.38156)
)

asks <- list(
  c(0.1435, 242.521842),
  c(0.1436, 206.49862099999999),
  c(0.1437, 205.823735),
  c(0.1438, 197.33275),
  c(0.1439, 153.677454),
  c(0.144, 146.007722),
  c(0.1442, 82.55212900000001),
  c(0.1443, 59.152814000000006),
  c(0.1444, 57.942260000000005),
  c(0.1445, 57.483850000000004),
  c(0.1446, 52.39210800000001),
  c(0.1447, 51.867208000000005),
  c(0.1448, 44.104697),
  c(0.1449, 40.131217),
  c(0.145, 31.878217),
  c(0.1451, 22.794916999999998),
  c(0.1453, 12.345828999999998),
  c(0.1454, 10.035642),
  c(0.148, 9.326642),
  c(0.1522, 3.76317)
)
```

# Set options

```{r}
#| label: set-options

options(
  highcharter.chart = list(
    accessibility = list(
      enabled = TRUE,
      linkedDescription = "A stock chart showing ETH-BTC market depth."
    )
  )
)
```

# Depth chart

```{r}
#| label: depth-chart

highchart(type = "chart") %>% 
  hc_chart(
    type = "area",
    zoomType = "xy"
  ) %>% 
  hc_title(
    text = "ETH-BTC Market Depth"
  ) %>% 
  hc_xAxis(
    minPadding = 0,
    maxPadding = 0,
    plotLines = list(
      list(
        color = "#888",
        value = 0.1523,
        width = 1,
        label = list(
          text = "Actual price",
          rotation = 90
        )
      )
    ),
    title = list(
      text = "Price"
    )
  ) %>% 
  hc_yAxis_multiples(
    list(
      lineWidth = 1,
      gridLineWidth = 1,
      title = NULL,
      tickWidth = 1,
      tickLength = 5,
      tickPosition = "inside",
      labels = list(
        align = "left",
        x = 8
      )
    ),
    list(
      opposite = TRUE,
      linkedTo = 0,
      lineWidth = 1,
      gridLineWidth = 0,
      title = NULL,
      tickWidth = 1,
      tickLength = 5,
      tickPosition = "inside",
      labels = list(
        align = "right",
        x = -8
      )
    )
  ) %>% 
  hc_legend(
    enabled = FALSE
  ) %>% 
  hc_plotOptions(
    area = list(
      fillOpacity = 0.2,
      lineWidth = 1,
      step = "center"
    )
  ) %>% 
  hc_tooltip(
    headerFormat = "<span style='font-size=10px'>Price: {point.key}</span><br>",
    valueDecimals = 2
  ) %>% 
  hc_add_series(
    name = "Bids",
    data = bids,
    color = "#03a7a8"
  ) %>% 
  hc_add_series(
    name = "Asks",
    data = asks,
    color = "#fc5887"
  )
```
