---
title: "Click to Add a Point Demo"
---

This is a demo of a line chart that allows users to update the data by clicking in the chart area.

Highcharts Demos: [Click to add a point](https://www.highcharts.com/demo/dynamic-click-to-add)

# Load packages

```{r}
#| label: load-packages
#| output: false

library(magrittr)
library(highcharter)
```

# Set options

```{r}
#| label: set-options

options(
  highcharter.chart = list(
    accessibility = list(
      enabled = TRUE,
      linkedDescription = "Chart allowing users to update the data by clicking in the chart area. Clicking an existing point will remove it.",
      announceNewData = list(
        enabled = TRUE
      )
    )
  )
)
```

# Highcharts Version 11 default color palette

```{r}
#| label: version-11-colors

colors_v11 <- c("#2caffe", "#544fc5", "#00e272", "#fe6a35", "#6b8abc", "#d568fb", "#2ee0ca", "#fa4b42", "#feb56a", "#91e8e1")
```

# Click to add a point

```{r}
#| label: click-add-point

highchartzero() %>% 
  hc_add_dependency("modules/exporting.js") %>% 
  hc_add_dependency("modules/export-data.js") %>% 
  hc_add_dependency("modules/accessibility.js") %>% 
  hc_colors(colors = colors_v11) %>% 
  hc_chart(
    type = "scatter",
    margin = c(70, 50, 60, 80),
    events = list(
      click = JS(
        "function (e) {
          // find the clicked values and the series
          var x = Math.round(e.xAxis[0].value),
              y = Math.round(e.yAxis[0].value),
              series = this.series[0];
          
          // Add it
          series.addPoint([x, y]);
        }"
      )
    )
  ) %>% 
  hc_title(
    text = "User supplied data",
    align = "left"
  ) %>% 
  hc_subtitle(
    text = "Click the plot area to add a point. Click a point to remove it.",
    align = "left"
  ) %>% 
  hc_xAxis(
    gridLineWidth = 1,
    minPadding = 0.2,
    maxPadding = 0.2,
    maxZoom = 60
  ) %>% 
  hc_yAxis(
    title = list(
      text = "Value"
    ),
    minPadding = 0.2,
    maxPadding = 0.2,
    maxZoom = 60,
    plotLines = list(
      list(
        value = 0,
        width = 1,
        color = "#808080"
      )
    )
  ) %>% 
  hc_legend(
    enabled = FALSE
  ) %>% 
  hc_exporting(
    enabled = FALSE
  ) %>% 
  hc_plotOptions(
    series = list(
      lineWidth = 1,
      point = list(
        events = list(
          click = JS(
            "function () {
              if(this.series.data.length > 1) {
                this.remove();
              }
            }"
          )
        )
      )
    )
  ) %>% 
  hc_add_series(
    data = list(
      c(20, 20),
      c(80, 80)
    )
  )
```
