---
title: "Pie Chart with Monochrome Fill Demo"
---

This is a demo of a pie chart with monochrome fill.

Highcharts Demos: [Pie with monochrome fill](https://www.highcharts.com/demo/pie-monochrome)

# Load packages

```{r}
#| label: load-packages
#| output: false

library(magrittr)
library(highcharter)
```

# Build data

Data retrieved from [NetMarketShare](https://netmarketshare.com/)

```{r}
#| label: build-data

df <- list(
  list(
    name = "Chrome",
    y = 74.03
  ),
  list(
    name = "Edge",
    y = 12.66
  ),
  list(
    name = "Firefox",
    y = 4.96
  ),
  list(
    name = "Safari",
    y = 2.49
  ),
  list(
    name = "Internet Explorer",
    y = 2.31
  ),
  list(
    name = "Other",
    y = 3.398
  )
)
```

# Set options

```{r}
#| label: set-options

options(
  highcharter.chart = list(
    accessibility = list(
      enabled = TRUE,
      linkedDescription = "Pie chart demonstrating a monochrome color scheme. Monochrome color schemes can make certain charts easier to understand, as it helps readers to focus on the content instead of the colors. There can also be accessibility benefits to using this kind of color scheme, both fo color blindness and tactile mediums, as long as there is a clear separation between slices.",
      point = list(
        valueSuffix = "%"
      )
    )
  )
)
```

# Define monochrome color palette

```{r}
#| label: monochrome-colors

colors <- list(
  JS("Highcharts.color(Highcharts.getOptions().colors[0]).brighten((0 - 3) / 7).get()"),
  JS("Highcharts.color(Highcharts.getOptions().colors[0]).brighten((1 - 3) / 7).get()"),
  JS("Highcharts.color(Highcharts.getOptions().colors[0]).brighten((2 - 3) / 7).get()"),
  JS("Highcharts.color(Highcharts.getOptions().colors[0]).brighten((3 - 3) / 7).get()"),
  JS("Highcharts.color(Highcharts.getOptions().colors[0]).brighten((4 - 3) / 7).get()"),
  JS("Highcharts.color(Highcharts.getOptions().colors[0]).brighten((5 - 3) / 7).get()"),
  JS("Highcharts.color(Highcharts.getOptions().colors[0]).brighten((6 - 3) / 7).get()"),
  JS("Highcharts.color(Highcharts.getOptions().colors[0]).brighten((7 - 3) / 7).get()"),
  JS("Highcharts.color(Highcharts.getOptions().colors[0]).brighten((8 - 3) / 7).get()"),
  JS("Highcharts.color(Highcharts.getOptions().colors[0]).brighten((9 - 3) / 7).get()")
)
```

# Pie chart with monochrome fill

```{r}
#| label: pie-with-monochrome-fill

highchartzero() %>% 
  hc_add_dependency("modules/exporting.js") %>% 
  hc_add_dependency("modules/export-data.js") %>% 
  hc_add_dependency("modules/accessibility.js") %>% 
  hc_chart(
    type = "pie",
    plotBackgroundColor = NULL,
    plotBorderWidth = NULL,
    plotShadow = FALSE
  ) %>% 
  hc_title(
    text = "Browser market shares in February, 2022",
    align = "left"
  ) %>% 
  hc_tooltip(
    pointFormat = "{series.name}: <b>{point.percentage:.1f}%</b>"
  ) %>% 
  hc_plotOptions(
    pie = list(
      allowPointSelect = TRUE,
      colors = colors,
      cursor = "pointer",
      borderRadius = 5,
      dataLabels = list(
        enabled = TRUE,
        format = "<b>{point.name}</b><br>{point.percentage:.1f} %",
        distance = -50,
        filter = list(
          property = "percentage",
          operator = ">",
          value = 4
        )
      )
    )
  ) %>% 
  hc_add_series(
    name = "Share",
    data = df
  )
```
