---
title: "Pie Chart with Drilldown Demo"
---

This is a demo of a pie chart with drilldown.

Highcharts Demos: [Pie with drilldown](https://www.highcharts.com/demo/pie-drilldown)

# Load packages

```{r}
#| label: load-packages
#| output: false

library(tibble)
library(dplyr)
library(forcats)
library(purrr)
library(highcharter)
```

# Build data

```{r}
#| label: build-data

# Demo data
df_browsers <- tibble(
  c("Chrome", "v65.0", 0.1),
  c("Chrome", "v64.0", 1.3),
  c("Chrome", "v63.0", 53.02),
  c("Chrome", "v62.0", 1.4),
  c("Chrome", "v61.0", 0.88),
  c("Chrome", "v60.0", 0.56),
  c("Chrome", "v59.0", 0.45),
  c("Chrome", "v58.0", 0.49),
  c("Chrome", "v57.0", 0.32),
  c("Chrome", "v56.0", 0.29),
  c("Chrome", "v55.0", 0.79),
  c("Chrome", "v54.0", 0.18),
  c("Chrome", "v51.0", 0.13),
  c("Chrome", "v49.0", 2.16),
  c("Chrome", "v48.0", 0.13),
  c("Chrome", "v47.0", 0.11),
  c("Chrome", "v43.0", 0.17),
  c("Chrome", "v29.0", 0.26),
  c("Safari", "v11.0", 3.39),
  c("Safari", "v10.1", 0.96),
  c("Safari", "v10.0", 0.36),
  c("Safari", "v9.1", 0.54),
  c("Safari", "v9.0", 0.13),
  c("Safari", "v5.1", 0.2),
  c("Firefox", "v58.0", 1.02),
  c("Firefox", "v57.0", 7.36),
  c("Firefox", "v56.0", 0.35),
  c("Firefox", "v55.0", 0.11),
  c("Firefox", "v54.0", 0.1),
  c("Firefox", "v52.0", 0.95),
  c("Firefox", "v51.0", 0.15),
  c("Firefox", "v50.0", 0.1),
  c("Firefox", "v48.0", 0.31),
  c("Firefox", "v47.0", 0.12),
  c("Edge", "v16", 2.6),
  c("Edge", "v15", 0.92),
  c("Edge", "v14", 0.4),
  c("Edge", "v13", 0.1),
  c("Opera", "v50.0", 0.96),
  c("Opera", "v49.0", 0.82),
  c("Opera", "v12.1", 0.14),
  c("Internet Explorer", "v11.0", 6.2),
  c("Internet Explorer", "v10.0", 0.29),
  c("Internet Explorer", "v9.0", 0.27),
  c("Internet Explorer", "v8.0", 0.47),
  c("Other", NA, 1.582)
) %>% 
  t() %>% 
  as_tibble() %>% 
  rename(
    browser = V1, 
    version = V2, 
    market_share = V3) %>% 
  mutate(
    browser = fct_inorder(browser),
    market_share = as.numeric(market_share)
  )

# Data for pie chart
df_browsers_pie <- df_browsers %>%
  group_by(browser) %>%
  summarise(market_share = sum(market_share)) %>%
  arrange(-market_share)

# Data for drilldown
df_browsers_drilldown <- df_browsers %>% 
  group_nest(browser) %>% 
  mutate(
    id = browser,
    type = "pie",
    data = map(
      data, mutate, name = version, y = market_share
    ),
    data = map(
      data, list_parse
    )
  )
```

# Set options

```{r}
#| label: set-options

options(
  highcharter.chart = list(
    accessibility = list(
      enabled = TRUE,
      linkedDescription = "Pie chart where the individual slices can be clicked to expose more detailed data.",
      announceNewData = list(
        enabled = TRUE
      ),
      point = list(
        valueSuffix = "%"
      )
    )
  )
)
```

# Highcharts Version 11 default color palette

```{r}
#| label: version-11-colors

colors_v11 <- c("#2caffe", "#544fc5", "#00e272", "#fe6a35", "#6b8abc", "#d568fb", "#2ee0ca", "#fa4b42", "#feb56a", "#91e8e1")
```

# Pie chart with drilldown

```{r}
#| label: pie-drilldown

highchartzero() %>% 
  hc_add_dependency("modules/drilldown.js") %>% 
  hc_add_dependency("modules/exporting.js") %>% 
  hc_add_dependency("modules/export-data.js") %>% 
  hc_add_dependency("modules/accessibility.js") %>% 
  hc_colors(colors = colors_v11) %>% 
  hc_title(
    text = "Browser market shares. January, 2022",
    align = "left"
  ) %>% 
  hc_subtitle(
    text = "Click the slices to view versions. Source: <a href='http://statcounter.com'>statcounter.com</a>",
    align = "left"
  ) %>% 
  hc_plotOptions(
    series = list(
      borderRadius = 5,
      dataLabels = list(
        enabled = TRUE,
        format = "{point.name}: {point.y:.1f}%"
      )
    )
  ) %>% 
  hc_tooltip(
    headerFormat = "<span style='font-size:11px'>{series.name}</span><br>",
    pointFormat = "<span style='color:{point.color}'>{point.name}</span>: <b>{point.y:.2f}%</b> of total<br>"
  ) %>% 
  hc_add_series(
    data = df_browsers_pie,
    type = "pie",
    hcaes(x = browser, y = market_share, name = browser, drilldown = browser),
    name = "Browsers",
    colorByPoint = TRUE
  ) %>% 
  hc_drilldown(
    allowPointDrilldown = TRUE,
    series = list_parse(df_browsers_drilldown)
  )
```
