---
title: "Line Styles Demo"
---

This is a demo of a chart demonstrating some line series styles.

Highcharts Demos: [Accessible line chart](https://www.highcharts.com/demo/accessible-line)

# Load packages

```{r}
#| label: load-packages
#| output: false

library(magrittr)
library(highcharter)
```

# Set options

```{r}
#| label: set-options

options(
  highcharter.chart = list(
    accessibility = list(
      enabled = TRUE,
      linkedDescription = "Line chart demonstrating some accessibility features of Highcharts. The chart displays the most commonly used screen readers in surveys taken by WebAIM from December 2010 to September 2019. JAWS was the most used screen reader until 2019, when NVDA took over. VoiceOver is the third most used screen reader, followed by Narrator. ZoomText/Fusion had a surge in 2015, but usage is otherwise low. The overall use of other screen readers has declined drastically the past few years."
    )
  )
)
```

# Highcharts Version 11 default color palette

```{r}
#| label: version-11-colors

colors_v11 <- c("#2caffe", "#544fc5", "#00e272", "#fe6a35", "#6b8abc", "#d568fb", "#2ee0ca", "#fa4b42", "#feb56a", "#91e8e1")
```

# Line styles

```{r}
#| label: line-styles

highchartzero() %>% 
  hc_add_dependency("modules/series-label.js") %>%
  hc_add_dependency("modules/exporting.js") %>% 
  hc_add_dependency("modules/export-data.js") %>% 
  hc_add_dependency("modules/accessibility.js") %>% 
  hc_add_dependency("themes/high-contrast-light.js") %>% 
  hc_chart(
    type = "spline"
  ) %>% 
  hc_legend(
    symbolWidth = 40
  ) %>% 
  hc_title(
    text = "Most common desktop screen readers",
    align = "left"
  ) %>% 
  hc_subtitle(
    text = "Source: WebAIM. Click on points to visit official screen reader website",
    align = "left"
  ) %>% 
  hc_yAxis(
    title = list(
      text = "Percentage usage"
    ),
    accessibility = list(
      description = "Percentage usage"
    )
  ) %>% 
  hc_xAxis(
    title = list(
      text = "Time"
    ),
    accessibility = list(
      description = "Time from December 2010 to September 2019"
    ),
    categories = list(
      "December 2010", "May 2012", "January 2014", "July 2015", "October 2017", "September 2019"
    )
  ) %>% 
  hc_tooltip(
    valueSuffix = "%",
    stickOnContact = TRUE
  ) %>% 
  hc_plotOptions(
    series = list(
      point = list(
        events = list(
          click = JS(
            "function () {
              window.location.href = this.series.options.website
            }"
          )
        )
      ),
      cursor = "pointer"
    )
  ) %>% 
  hc_add_series(
    name = "NVDA",
    data = c(34.8, 43.0, 51.2, 41.4, 64.9, 72.4),
    website = "https://www.nvaccess.org",
    color = colors_v11[3],
    accessibility = list(
      description = "This is the most used screen reader in 2019"
    )
  ) %>% 
  hc_add_series(
    name = "JAWS",
    data = c(69.6, 63.7, 63.9, 43.7, 66.0, 61.7),
    website = "https://www.freedomscientific.com/Products/Blindness/JAWS",
    dashStyle = "ShortDashDot",
    color = colors_v11[1]
  ) %>% 
  hc_add_series(
    name = "VoiceOver",
    data = c(20.2, 30.7, 36.8, 30.9, 39.6, 47.1),
    website = "http://www.apple.com/accessibility/osx/voiceover",
    dashStyle = "ShortDot",
    color = colors_v11[2]
  ) %>% 
  hc_add_series(
    name = "Narrator",
    data = list(NA, NA, NA, NA, 21.4, 30.3),
    website = "https://support.microsoft.com/en-us/help/22798/windows-10-complete-guide-to-narrator",
    dashStyle = "Dash",
    color = colors_v11[10]
  ) %>% 
  hc_add_series(
    name = "ZoomText/Fusion",
    data = c(6.1, 6.8, 5.3, 27.5, 6.0, 5.5),
    website = "http://www.zoomtext.com/products/zoomtext-magnifierreader",
    dashStyle = "ShortDot",
    color = colors_v11[6]
  ) %>% 
  hc_add_series(
    name = "Other",
    data = c(42.6, 51.5, 54.2, 45.8, 20.2, 15.4),
    website = "http://www.disabled-world.com/assistivedevices/computer/screen-readers.php",
    dashStyle = "ShortDash",
    color = colors_v11[4]
  ) %>% 
  hc_responsive(
    rules = list(
      list(
        condition = list(
          maxWidth = 550
        ),
        chartOptions = list(
          chart = list(
            spacingLeft = 3,
            spacingRight = 3
          ),
          legend = list(
            itemWidth = 150
          ),
          xAxis = list(
            categories = list(
              "December 2010", "May 2012", "January 2014", "July 2015", "October 2017", "September 2019"
            ),
            title = NULL
          ),
          yAxis = list(
            visible = FALSE
          )
        )
      )
    )
  )
```
