---
title: "Stock Chart with Flag Shapes and Colors Demo"
---

This is a demo of a line stock chart with flag shapes and colors.

Highcharts Stock Demos: [Flags shapes and colors](https://www.highcharts.com/demo/stock/flags-shapes)

# Load packages

```{r}
#| label: load-packages
#| output: false

library(dplyr)
library(jsonlite)
library(highcharter)
```

# Import data

```{r}
#| label: import-data

usd_eur <- fromJSON("data/usdeur.json")
```

# Set options

```{r}
#| label: set-options

options(
  highcharter.chart = list(
    accessibility = list(
      enabled = TRUE,
      linkedDescription = "A line stock chart showing USD to EUR exchange rate. Squarepin flags are placed on series, and circlepin flags are placed on axis."
    )
  )
)
```

# Highcharts Version 11 default color palette

```{r}
#| label: version-11-colors

colors_v11 <- c("#2caffe", "#544fc5", "#00e272", "#fe6a35", "#6b8abc", "#d568fb", "#2ee0ca", "#fa4b42", "#feb56a", "#91e8e1")
```

# Flags shapes and colors

```{r}
#| label: flags-shapes-and-colors

highchart(type = "stock") %>% 
  hc_colors(colors = colors_v11) %>% 
  hc_rangeSelector(
    selected = 4
  ) %>% 
  hc_title(
    text = "USD to EUR exchange rate"
  ) %>% 
  hc_yAxis(
    title = list(
      text = "Exchange rate"
    )
  ) %>% 
  hc_plotOptions(
    flags = list(
      accessibility = list(
        exposeAsGroupOnly = TRUE,
        description = "Flagged events."
      )
    )
  ) %>% 
  hc_add_series(
    type = "line",
    name = "USD to EUR",
    data = usd_eur,
    id = "dataseries",
    tooltip = list(
      valueDecimals = 4
    )
  ) %>% 
  hc_add_series(
    type = "flags",
    data = list(
      list(
        x = JS("Date.UTC(2021, 1, 22)"),
        title = "A",
        text = "Shape: 'squarepin'"
      ),
      list(
        x = JS("Date.UTC(2021, 3, 28)"),
        title = "A",
        text = "Shape: 'squarepin'"
      )
    ),
    onSeries = "dataseries",
    shape = "squarepin",
    width = 16
  ) %>% 
  hc_add_series(
    type = "flags",
    data = list(
      list(
        x = JS("Date.UTC(2021, 2, 1)"),
        title = "B",
        text = "Shape: 'circlepin'"
      ),
      list(
        x = JS("Date.UTC(2021, 3, 1)"),
        title = "B",
        text = "Shape: 'circlepin'"
      )
    ),
    shape = "circlepin",
    width = 16
  ) %>% 
  hc_add_series(
    type = "flags",
    data = list(
      list(
        x = JS("Date.UTC(2021, 2, 10)"),
        title = "C",
        text = "Shape: 'flag'"
      ),
      list(
        x = JS("Date.UTC(2021, 3, 11)"),
        title = "C",
        text = "Shape: 'flag'"
      )
    ),
    color = colors_v11[1], # same as OnSeries
    fillColor = colors_v11[1],
    onSeries = "dataseries",
    width = 16,
    style = list(
      color = "white" # text style
    ),
    states = list(
      hover = list(
        fillColor = "#395C84" # darker
      )
    )
  )
```
