---
title: "Area Range Chart with Line Series Demo"
---

This is a demo of an area range chart with a line series.

Highcharts Demos: [Area range and line](https://www.highcharts.com/demo/arearange-line)

# Load packages

```{r}
#| label: load-packages
#| output: false

library(tibble)
library(dplyr)
library(highcharter)
```

# Build data

```{r}
#| label: build-data

ranges <- tibble(
  c(13.7, 25.6),
  c(13.3, 21.8),
  c(11.2, 19.9),
  c(7.9, 17.3),
  c(4.9, 20.6),
  c(5.1, 16.8),
  c(9.3, 21.1),
  c(11.1, 20.5),
  c(8.9, 18.4),
  c(4.6, 23.2),
  c(11.5, 26.0),
  c(8.6, 23.4),
  c(9.8, 22.2),
  c(8.1, 18.2),
  c(5.9, 20.2),
  c(4.5, 20.2),
  c(8.9, 19.8),
  c(11.1, 22.1),
  c(7.9, 26.7),
  c(15.9, 28.6),
  c(14.9, 27.5),
  c(9.5, 26.0),
  c(11.5, 22.4),
  c(8.6, 21.1),
  c(12.9, 21.7),
  c(13.6, 20.9),
  c(9.6, 23.9),
  c(8.6, 22.7),
  c(7.5, 25.7),
  c(5.5, 24.3),
  c(10.4, 21.2)
) %>% 
  t() %>% 
  as_tibble() %>% 
  rename(
    low_temperaturec = V1,
    high_temperaturec = V2
  )

averages = c(
  18.1,
  17.1,
  15.2,
  12.7,
  13.3,
  10.6,
  15.6,
  16.1,
  14.0,
  15.3,
  17.5,
  17.5,
  15.3,
  13.9,
  13.7,
  13.8,
  14.0,
  15.8,
  18.6,
  21.5,
  19.8,
  17.6,
  16.8,
  15.6,
  16.7,
  16.3,
  17.2,
  16.0,
  16.9,
  16.1,
  14.5
)
```

# Set options

```{r}
#| label: set-options

options(
  highcharter.chart = list(
    accessiblility = list(
      enabled = TRUE,
      linkedDescription = "Chart demonstrating using an arearange series in combination with a line series. In this case, the arearange series is used to visualize the temperature range per day, while the line series shows the average temperature."
    )
  )
)
```

# Highcharts Version 11 default color palette

```{r}
#| label: version-11-colors

colors_v11 <- c("#2caffe", "#544fc5", "#00e272", "#fe6a35", "#6b8abc", "#d568fb", "#2ee0ca", "#fa4b42", "#feb56a", "#91e8e1")
```

# Area range and line

```{r}
#| label: area-range-with-line

highchartzero() %>% 
  hc_add_dependency("highcharts-more.js") %>% 
  hc_add_dependency("modules/exporting.js") %>%
  hc_add_dependency("modules/export-data.js") %>%
  hc_add_dependency("modules/accessibility.js") %>%
  hc_colors(colors = colors_v11) %>% 
  hc_title(
    text = "July temperatures in Nesbyen, 2022",
    align = "left"
  ) %>% 
  hc_subtitle(
    text = "Source: <a href='https://www.yr.no/nb/historikk/graf/1-113585/Norge/Viken/Nesbyen/Nesbyen?q=2022-07'>YR</a>",
    align = "left"
  ) %>% 
  hc_xAxis(
    title = list(
      text = NULL
    ),
    type = "datetime",
    accessibility = list(
      rangeDescription = "Range: Jul 1st 2022 to Jul 31st 2022."
    )
  ) %>% 
  hc_yAxis(
    title = list(
      text = FALSE
    )
  ) %>% 
  hc_tooltip(
    crosshairs = TRUE,
    shared = TRUE,
    valueSuffix = "°C"
  ) %>% 
  hc_plotOptions(
    series = list(
      pointStart = JS("Date.UTC(2022, 6, 1)"),
      pointIntervalUnit = "day"
    )
  ) %>% 
  hc_add_series(
    name = "Temperature",
    data = averages,
    zIndex = 1,
    marker = list(
      fillColor = "white",
      lineWidth = 2,
      lineColor = "#7cb5ec"
    )
  ) %>% 
  hc_add_series(
    name = "Range",
    data = ranges,
    type = "arearange",
    hcaes(low = low_temperaturec, high = high_temperaturec),
    lineWidth = 0,
    linkedTo = ":previous",
    color = "#7cb5ec",
    fillOpacity = 0.3,
    zIndex = 0,
    marker = list(
      enabled = FALSE
    )
  )
```
