---
title: "Area Chart with Negative Values Demo"
---

This is a demo of an area chart with negative values.

Highcharts Demos: [Area with negative values](https://www.highcharts.com/demo/area-negative)

# Load packages

```{r}
#| label: load-packages
#| output: false

library(tidyr)
library(dplyr)
library(forcats)
library(highcharter)
```

# Build data

```{r}
#| label: build-data

df <- tibble(
  quarter = c(
    "Q1 2019", "Q2 2019", "Q3 2019", "Q4 2019", 
    "Q1 2020", "Q2 2020", "Q3 2020", "Q4 2020", 
    "Q1 2021", "Q2 2021", "Q3 2021"
  ),
  `Total production` = c(
    37.8, 29.3, 30.8, 36.8, 40.5, 35.3, 34.9, 43.6, 45.7, 35.9, 32.7
  ),
  `Gross consumption` = c(
    39.9, 29.9, 26.7, 38.1, 39.3, 30.2, 27.5, 36.7, 42.7, 31.4, 27.5
  ),
  `Trade surplus` = c(
    -2.2, -0.6, 4.1, -1.3, 1.2, 5.1, 7.4, 6.9, 2.9, 4.5, 5.2
  )
) %>% 
  pivot_longer(
    cols = !quarter,
    names_to = "name",
    values_to = "value"
  ) %>% 
  mutate(
    quarter = as_factor(quarter),
    name = as_factor(name)
  )
```

# Set options

```{r}
#| label: set-options

options(
  highcharter.chart = list(
    accessiblility = list(
      enabled = TRUE,
      linkedDescription = "A simple demo showcasing an area chart with negative values and multiple data series. Note that interacting with one data series will dim the others, making it easier to distinguish between them."
    )
  )
)
```

# Highcharts Version 11 default color palette

```{r}
#| label: version-11-colors

colors_v11 <- c("#2caffe", "#544fc5", "#00e272", "#fe6a35", "#6b8abc", "#d568fb", "#2ee0ca", "#fa4b42", "#feb56a", "#91e8e1")
```

# Area chart with negative values

```{r}
#| label: area-with-negative-values

highchartzero() %>% 
  hc_add_dependency("modules/exporting.js") %>%
  hc_add_dependency("modules/export-data.js") %>%
  hc_add_dependency("modules/accessibility.js") %>%
  hc_colors(colors = colors_v11) %>% 
  hc_title(
    text = "Production, consumption and trade surplus of electrical power",
    align = "left"
  ) %>% 
  hc_subtitle(
    text = "Source: <a href='https://www.ssb.no/energi-og-industri/energi/statistikk/elektrisitet/artikler/lavere-kraftproduksjon'>SSB</a>",
    align = "left"
  ) %>% 
  hc_xAxis(
    title = list(
      text = NULL
    ),
    categories = unique(df$quarter)
  ) %>% 
  hc_yAxis(
    title = list(
      text = "TWh"
    )
  ) %>% 
  hc_credits(
    enabled = FALSE
  ) %>% 
  hc_add_series(
    data = df,
    type = "area",
    hcaes(x = quarter, y = value, group = name)
  ) 
```
