---
title: "Percentage Stacked Area Chart Demo"
---

This is a demo of a percentage stacked area chart.

Highcharts Demos: [Percentage area](https://www.highcharts.com/demo/area-stacked-percent)

# Load packages

```{r}
#| label: load-packages
#| output: false

library(tidyr)
library(dplyr)
library(forcats)
library(highcharter)
```

# Build data

```{r}
#| label: build-data

df <- tibble(
  year = seq.int(from = 1990, to = 2021, by = 1),
  China = c(
    2.5, 2.6, 2.7, 2.9, 3.1, 3.4, 3.5, 3.5, 3.4, 3.4, 
    3.4, 3.5, 3.9, 4.5, 5.2, 5.9, 6.5, 7, 7.5, 7.9, 
    8.6, 9.5, 9.8, 10, 10, 9.8, 9.7, 9.9, 10.3, 10.5, 
    10.7, 10.9
  ),
  USA = c(
    5.1, 5.1, 5.2, 5.3, 5.4, 5.4, 5.6, 5.7, 5.7, 5.8, 
    6, 5.9, 5.9, 6, 6.1, 6.1, 6.1, 6.1, 5.9, 5.5, 
    5.7, 5.5, 5.3, 5.5, 5.5, 5.4, 5.2, 5.2, 5.4, 5.3, 
    4.7, 5
  ),
  EU = c(
    3.9, 3.8, 3.7, 3.6, 3.6, 3.6, 3.7, 3.7, 3.6, 3.6, 
    3.6, 3.7, 3.7, 3.7, 3.8, 3.7, 3.7, 3.7, 3.6, 3.3, 
    3.4, 3.3, 3.3, 3.2, 3, 3.1, 3.1, 3.1, 3, 2.9, 
    2.6, 2.7
  ),
  India = c(
    0.6, 0.6, 0.7, 0.7, 0.7, 0.8, 0.8, 0.9, 0.9, 1, 
    1, 1, 1, 1.1, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 
    1.7, 1.8, 2, 2, 2.2, 2.3, 2.4, 2.4, 2.6, 2.6, 
    2.4, 2.7
  )
) %>% 
  pivot_longer(
    cols = !year,
    names_to = "country",
    values_to = "co2_emissions"
  ) %>% 
  mutate(
    year = as.integer(year),
    country = as_factor(country)
  )
```

# Set options

```{r}
#| label: set-options

options(
  highcharter.chart = list(
    accessiblility = list(
      enabled = TRUE,
      linkedDescription = "Chart demonstrating a percentage-stacked area chart, a variation of the stacked area chart where each data series is visualized as a running percentage of the total.",
      point = list(
        valueDescriptionFormat = "{index}. {point.category}, {point.y:,.1f} billions, {point.percentage:.1f}%."
      )
    )
  )
)
```

# Highcharts Version 11 default color palette

```{r}
#| label: version-11-colors

colors_v11 <- c("#2caffe", "#544fc5", "#00e272", "#fe6a35", "#6b8abc", "#d568fb", "#2ee0ca", "#fa4b42", "#feb56a", "#91e8e1")
```

# Percentage stacked area chart

```{r}
#| label: percentage-area

highchartzero() %>% 
  hc_add_dependency("modules/series-label.js") %>% 
  hc_add_dependency("modules/exporting.js") %>%
  hc_add_dependency("modules/export-data.js") %>%
  hc_add_dependency("modules/accessibility.js") %>%
  hc_colors(colors = colors_v11) %>% 
  hc_title(
    useHTML = TRUE,
    text = "Countries/regions with highest Gt CO<sub>2</sub>-emissions",
    align = "left"
  ) %>% 
  hc_subtitle(
    text = "Source: <a href='https://energiogklima.no/klimavakten/land-med-hoyest-utslipp/'>Energi og Klima</a>",
    align = "left"
  ) %>% 
  hc_yAxis(
    title = list(
      text = FALSE
    ),
    labels = list(
      format = "{value}%"
    )
  ) %>% 
  hc_tooltip(
    pointFormat = "<span style='color:{series.color}'>{series.name}</span>: <b>{point.percentage:.1f}%</b> ({point.y:,.1f} billion Gt)<br/>",
    split = TRUE
  ) %>% 
  hc_plotOptions(
    series = list(
      pointStart = 1990
    ),
    area = list(
      stacking = "percent",
      marker = list(
        enabled = FALSE
      )
    )
  ) %>% 
  hc_add_series(
    data = df,
    type = "area",
    hcaes(x = year, y = co2_emissions, group = country)
  ) 
```
