---
title: "Stacked Area Chart Demo"
---

This is a demo of a stacked area chart.

Highcharts Demos: [Stacked area](https://www.highcharts.com/demo/area-stacked)

# Load packages

```{r}
#| label: load-packages
#| output: false

library(tidyr)
library(dplyr)
library(forcats)
library(highcharter)
```

# Build data

```{r}
#| label: build-data

df <- tibble(
  year = seq.int(from = 2012, to = 2020, by = 1),
  `Ocean transport` = c(
    13234, 12729, 11533, 17798, 10398, 12811, 15483, 16196, 16214
  ),
  Households = c(
    6685, 6535, 6389, 6384, 6251, 5725, 5631, 5047, 5039
  ),
  `Agriculture and hunting` = c(
    4752, 4820, 4877, 4925, 5006, 4976, 4946, 4911, 4913
  ),
  `Air transport` = c(
    3164, 3541, 3898, 4115, 3388, 3569, 3887, 4593, 1550
  ),
  Construction = c(
    2019, 2189, 2150, 2217, 2175, 2257, 2344, 2176, 2186
  )
) %>% 
  pivot_longer(
    cols = !year,
    names_to = "economic_activity",
    values_to = "greenhouse_gases"
  ) %>% 
  mutate(
    year = as.integer(year),
    economic_activity = as_factor(economic_activity)
  )
```

# Set options

```{r}
#| label: set-options

options(
  highcharter.chart = list(
    accessiblility = list(
      enabled = TRUE,
      linkedDescription = "A demo showing a stacked area chart, also sometimes referred to as a mountain chart. In a stacked chart, the data series values are added together to make up a total."
    )
  )
)
```

# Highcharts Version 11 default color palette

```{r}
#| label: version-11-colors

colors_v11 <- c("#2caffe", "#544fc5", "#00e272", "#fe6a35", "#6b8abc", "#d568fb", "#2ee0ca", "#fa4b42", "#feb56a", "#91e8e1")
```

# Stacked area

```{r}
#| label: stacked-area

highchartzero() %>% 
  hc_add_dependency("modules/exporting.js") %>%
  hc_add_dependency("modules/export-data.js") %>%
  hc_add_dependency("modules/accessibility.js") %>%
  hc_colors(colors = colors_v11) %>% 
  hc_title(
    text = "Greenhouse gases from Norwegian economic activity",
    align = "left"
  ) %>% 
  hc_subtitle(
    text = "Source: <a href='https://www.ssb.no/en/statbank/table/09288/'>SSB</a>",
    align = "left"
  ) %>% 
  hc_xAxis(
    title = list(
      text = NULL
    )
  ) %>% 
  hc_yAxis(
    useHTML = TRUE,
    title = list(
      text = "Million tonnes CO<sub>2</sub>-equivalents"
    )
  ) %>% 
  hc_tooltip(
    shared = TRUE,
    headerFormat = "<span style='font-size:12px'><b>{point.x}</b></span><br>"
  ) %>% 
  hc_plotOptions(
    series = list(
      pointStart = 2012
    ),
    area = list(
      stacking = "normal",
      lineColor = "#666666",
      lineWidth = 1,
      marker = list(
        lineWidth = 1,
        lineColor = "#666666"
      )
    )
  ) %>% 
  hc_add_series(
    data = df,
    type = "area",
    hcaes(x = year, y = greenhouse_gases, group = economic_activity)
  ) 
```
